### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getText' of undefined

### ISSUE THREAD

**Issue by mandisimakwakwa** [stevemao/atom-conventional-changelog#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.4.15
**OS**: "Manjaro Linux"
**Thrown From**: [conventional-changelog](https://github.com/stevemao/atom-conventional-changelog) package 0.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getText' of undefined

```
At /home/novice/.atom/packages/conventional-changelog/index.js:67

TypeError: Cannot read property 'getText' of undefined
    at /packages/conventional-changelog/index.js:67:20)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/lib/atom/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/lib/atom/src/atom-environment.js:1179:28)
    at EventEmitter.outerCallback (/usr/lib/atom/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -5:23.7.0 core:paste (input.hidden-input)
     -5:19.7.0 intentions:highlight (input.hidden-input)
     -5:19.5.0 core:paste (input.hidden-input)
  2x -5:13.1.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-light-ui)
     -4:52.9.0 core:save (input.hidden-input)
     -4:42.1.0 atom-github-issues:open (p.)
     -2:03.7.0 core:confirm (input.hidden-input)
  7x -1:52.9.0 core:backspace (input.hidden-input)
     -1:12.5.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-light-ui)
     -1:03.1.0 atom-force:toggle (div.package-detail.panels-item)
     -0:51.8.0 atom-force:addForceNature (div.package-readme.native-key-bindings)
     -0:43.4.0 atom-github-notifications:reset (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-light-ui)
     -0:38.2.0 atom-github-notifications:fetch (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-light-ui)
     -0:31.5.0 atom-latex:build (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-light-ui)
     -0:14 codelf:search (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-light-ui)
     -0:03.4.0 conventional-changelog:changelog (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-light-ui)
```

### Non-Core Packages

```
atom-force 0.3.4 
atom-github-issues 0.4.3 
atom-github-notifications 0.3.0 
atom-latex 0.7.8 
bugzilla-number 0.1.0 
busy-signal 1.4.1 
clipboard-autocomplete 0.4.0 
codelf 5.1.0 
comments-42 1.3.0 
conventional-changelog 0.1.0 
create-github-repo 1.1.2 
flickr-background 0.4.5 
fold-functions 0.5.0 
ftp-remote-edit 0.9.4 
gist-it 0.9.2 
git-checkout 0.3.2 
git-commit 1.5.3 
git-control 0.9.0 
git-diff-details 1.4.0 
git-grep 0.9.0 
git-line 0.6.0 
git-log 0.4.1 
git-plus 7.8.0 
git-projects 1.17.0 
git-status 0.3.4 
git-time-machine 1.5.9 
github-issues 0.8.3 
github-notifications 0.1.2 
github-plus 1.0.0 
github-search 0.1.0 
github-url-resolver 0.1.1 
github-user-datatip 0.3.2 
github-utils 1.6.0 
gitignore-snippets 0.2.5 
grammar-token-limit 0.1.1 
header-42 0.3.3 
hyperclick 0.0.40 
imdone-atom-github 0.1.11 
intentions 1.1.2 
json-generator 0.1.15 
language-markdown 0.22.0 
language-unix-shell 0.40.1 
line-count 0.5.0 
linter 2.1.4 
linter-lesshint 3.0.2 
linter-ui-default 1.2.4 
MagicPython 1.0.10 
my-github-profile 0.2.1 
norminette-linter 0.3.1 
octophus 0.1.1 
open-git-modified-files 0.2.4 
open-github-from-npm 0.1.1 
open-in-github-app 0.2.6 
pull-request 0.2.1 
remote-atom 1.3.10 
remote-atom-plus 0.1.0 
remote-edit 1.9.0 
Remote-FTP 0.10.7 
remote-sync 4.1.5 
ruby-bundler 0.3.0 
SFTP-deployment 1.0.2 
show-repository-web 0.1.2 
ssh-config 0.10.1 
titanium-alloy 0.13.9 
tree-view-git-branch 0.1.2 
tree-view-git-status 1.3.1 
```

**Comment by mandisimakwakwa** [comment]
Atom Gihub Token Issue
