### ISSUE TITLE
Failed to load the conventional-changelog package

### ISSUE THREAD

**Issue by jcdalton2201** [stevemao/atom-conventional-changelog#6]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [conventional-changelog](https://github.com/stevemao/atom-conventional-changelog) package 0.1.0

### Stack Trace

Failed to load the conventional-changelog package

```
At Cannot find module 'concat-stream'

Error: Cannot find module 'concat-stream'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Users/fpt595/Downloads/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Users/fpt595/Downloads/Atom.app/Contents/Resources/app/src/module-cache.js:354:1)
    at Module.require (Users/fpt595/Downloads/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (/Users/fpt595/Downloads/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:1)
    at /packages/atom-conventional-changelog-master/index.js:9:21)
    at Module.get_Module._compile (/Users/fpt595/Downloads/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .js] (/Users/fpt595/Downloads/Atom.app/Contents/Resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (Users/fpt595/Downloads/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Users/fpt595/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:73:1)
    at Package.module.exports.Package.requireMainModule (/Users/fpt595/Downloads/Atom.app/Contents/Resources/app/src/package.js:887:1)
    at /Users/fpt595/Downloads/Atom.app/Contents/Resources/app/src/package.js:158:1
    at Package.module.exports.Package.measure (/Users/fpt595/Downloads/Atom.app/Contents/Resources/app/src/package.js:99:1)
    at Package.module.exports.Package.load (/Users/fpt595/Downloads/Atom.app/Contents/Resources/app/src/package.js:144:1)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (/Users/fpt595/Downloads/Atom.app/Contents/Resources/app/src/package-manager.js:562:1)
    at /Users/fpt595/Downloads/Atom.app/Contents/Resources/app/src/package-manager.js:476:1
    at Config.module.exports.Config.transact (/Users/fpt595/Downloads/Atom.app/Contents/Resources/app/src/config.js:321:1)
    at PackageManager.module.exports.PackageManager.loadPackages (/Users/fpt595/Downloads/Atom.app/Contents/Resources/app/src/package-manager.js:470:1)
    at /Users/fpt595/Downloads/Atom.app/Contents/Resources/app/src/atom-environment.js:798:1
```

### Commands

```
     -0:19 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -0:07.3.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
angularjs 0.4.0 
atom-beautify 0.29.26 
conventional-changelog 0.1.0 
atom-typescript 11.0.3 
busy-signal 1.4.3 
copy-as-rtf 0.9.3 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.7 
hyperclick 0.0.40 
intentions 1.1.2 
js-hyperclick 1.11.0 
linter 2.1.4 
linter-eslint 8.2.1 
linter-ui-default 1.6.0 
markdown-pdf 1.5.0 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
northem-dark-atom-syntax 2.1.0 
nucleus-dark-ui 0.12.3 
remote-sync 4.1.5 
```

**Comment by stevemao** [comment]
Have you tried to reinstall the package?
